function frd_pipeline_2_automized

clear all

load('Y:\MRI\Human\fMRI-reach-decision\Experiment\behavioral_data\protocols_v2.mat');

throwaway = ~strcmp('CLSC',{prot.name});
prot(throwaway) = [];



runpath = 'D:\Experiment';

save('D:\Experiment\buffer_for_pipleine_2.mat','prot', 'runpath')

for i = 1:length(prot)
    
    sessions = length(prot(i).session);
    
    for k = 1:sessions
        
%         ne_pl_process_one_session_3TUMG_part2(...
%             'Y:\MRI\Human\fMRI-reach-decision\Pilot\MAPA\20190802',...
%             'MAPA',...
%             'Human_reach_decision',...
%             {'all'},...
%             'prt2avg_script',...
%             'ne_prt2avg_reach_decision_pilot',... % ????????
%             'vmr_pattern',...
%             '.vmr',...
%             'sdm_pattern',...
%             '*_outlier_preds.sdm');
        
        
        ne_pl_process_one_session_3TUMG_part2(...
            [runpath filesep prot(i).name filesep prot(i).session(k).date],...
            [prot(i).name '_' prot(i).session(k).date],...
            'Human_reach_decision',...
            {'all'},...
            'prt2avg_script',...
                'ne_prt2avg_reach_decision_pilot',...
            'vmr_pattern',...
                '.vmr',...
            'sdm_pattern',...
                '*_outlier_preds.sdm');
        
        
        save('D:\Experiment\buffer_for_pipleine_2.mat','prot', 'runpath','i','k')
        memory
        inmem
        
        clear all
        
        load('D:\Experiment\buffer_for_pipleine_2.mat')
        memory
        inmem
        
    end
end


