function frd_pipeline3_automized
clear all

load('Y:\MRI\Human\fMRI-reach-decision\Experiment\behavioral_data\protocols_v2.mat');
% throwaway = strcmp('OLPE',{prot.name}) | ...
%     strcmp('ELRH',{prot.name}) |...
%     strcmp('CLSC',{prot.name}) |...
%     strcmp('DAGU',{prot.name}) |...
%     strcmp('CLSC',{prot.name}) |...
%     strcmp('EVBO',{prot.name}) |...
%     strcmp('NORE',{prot.name}) |...
%     strcmp('LORU',{prot.name}) |...
%     strcmp('ANEL',{prot.name}) ;

% throwaway = ~strcmp('LORU',{prot.name});
% prot(throwaway) = [];
prot(9).session(2) = [];



runpath = 'D:\Experiment';
save('D:\Experiment\buffer_for_pipleine_3_avg_automized.mat','prot', 'runpath')

for i = 1:length(prot)
    
    %% create avg´s
    
    % ne_pl_multisession_3TUMG_part2(...
    %     'Y:\MRI\Human\fMRI-reach-decision\Pilot\MAPA',...
    %     {'20*'},...
    %     '',...
    %     'MAPA_combined',...
    %     '*no_outliers.avg',...
    %     'Human_reach_decision_pilot',...
    %     {'all'},...
    %     'sdm_pattern',...
    %         '*outlier_preds.sdm');
    
    ne_pl_multisession_3TUMG_part2(...
        [runpath filesep prot(i).name],...
        {prot(i).session().date},...
        '',...
        [prot(i).name '_combined'],...
        '*no_outliers.avg',...
        'Human_reach_decision',... % (see ne_pl_session_settings.m)
        {'all'},...
        'sdm_pattern',...
        '*outlier_preds.sdm');
    
    
    %% take care of memory
    save('D:\Experiment\buffer_for_pipleine_3_avg_automized.mat','prot', 'runpath','i')
    memory
    inmem
    
    clear all
    
    load('D:\Experiment\buffer_for_pipleine_3_avg_automized.mat')
    memory
    inmem
    
    
end
